# Generated by Django 4.1.1 on 2022-12-17 17:27

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='video',
            field=models.FileField(default=False, upload_to='video/%y', validators=[base.validators.file_size]),
        ),
    ]
