# Generated by Django 4.1.1 on 2022-12-17 17:38

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='video',
            field=models.FileField(upload_to='video/%y', validators=[base.validators.file_size]),
        ),
    ]
