# Generated by Django 4.1.1 on 2022-12-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
