# Generated by Django 4.1.1 on 2022-12-19 21:17

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_publictask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y', validators=[base.validators.file_size]),
        ),
    ]
