# Generated by Django 4.1.1 on 2022-12-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_task_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicTask',
        ),
    ]
