# Generated by Django 4.1.1 on 2022-12-20 11:58

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_task_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['media']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='video',
        ),
        migrations.AddField(
            model_name='task',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/%y', validators=[base.validators.file_size]),
        ),
    ]
